[package]
name = "parse_md"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
serve_md_core = { path = "../../crates/core" }
clap = { version = "4.3.23", features = ["derive"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true
panic = "abort"
