name: Build

on:
  workflow_dispatch:
  push:
    brances:
      - main

jobs:
  check-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    uses: ./.github/workflows/test.yaml
          
  build-upload-assets:
    needs: check-test

    strategy:
      matrix:
        binary: [parse_md, serve_md]
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: Build ${{ matrix.binary }} release on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install stable rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Cache rust
        uses: Swatinem/rust-cache@v2
      - name: Build binary ${{ matrix.binary }}
        run: cargo build --release --manifest-path binary/${{ matrix.binary }}/Cargo.toml
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.binary }}-${{ matrix.os }}
          path: |
            binary/${{ matrix.binary }}/target/release/${{ matrix.binary }}*
            !binary/${{ matrix.binary }}/target/release/${{ matrix.binary }}.d*