name: Build

on:
  workflow_dispatch:
  push:
    brances:
      - main

jobs:
  build-upload-assets:
    strategy:
      matrix:
        binary: [parse_md, serve_md]
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rust-build/rust-build.action@v1.4.3
        env:
          SRC_DIR: 'binary/${{ matrix.binary }}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          UPLOAD_MODE: none
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}