name: Test _md

on:
  workflow_dispatch
  pull_request:
  push:
    brances:
      - main

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo check
      - run: cargo test