name: Test _md

on:
  pull_request:
  push:
    brances:
      - main

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo check
      - run: cargo test