name: Run tests for `{core/async}_md` crates.

on:
  workflow_dispatch:
  pull_request:
  push:
    brances:
      - main

jobs:
  cargo-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: Test & check with `cargo check/test` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo check
      - run: cargo test